export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER ="LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//projectAction
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";
export const MODIFY_SUCCESS = "MODIFY_SUCCESS";
export const MODIFY_FAILURE = "MODIFY_FAILURE";
export const PROJECT_DELETE = "PROJECT_DELETE";
export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";
export const GET_ALL_PROJECT = "GET_ALL_PROJECT";